minimumLimaVersion: 2.2.0
vmType: vz
arch: aarch64
nestedVirtualization: false
propagateProxyEnv: false
cpus: 16
memory: 64GiB
disk: 128GiB
user:
  name: pgrac
  comment: PGRAC image operator
  home: /home/pgrac
  uid: 1000
images:
  - location: ./pre2-single-arm64.qcow2
    arch: aarch64
mounts: []
containerd:
  system: false
  user: false
ssh:
  loadDotSSHPubKeys: false
  forwardAgent: false
portForwards:
  - guestIP: 0.0.0.0
    proto: any
    guestPortRange: [1, 65535]
    ignore: true
