/*-------------------------------------------------------------------------
 *
 * test_cluster_r4_slot_machine.c
 *	  Stage 8 R4 closed 10-state by 9-event operation matrix.
 *
 *-------------------------------------------------------------------------
 */
#include "postgres.h"

#include "cluster/cluster_cr_server.h"
#include "cluster/cluster_gcs_block.h"
#include "cluster/cluster_lms.h"

#undef printf

#include "unit_test.h"

UT_DEFINE_GLOBALS();

#define NONE CLUSTER_R4_STATE_INVALID
#define REQ CLUSTER_R4_OWNER_REQUESTER
#define ROUTE (CLUSTER_R4_OWNER_REQUESTER | CLUSTER_R4_OWNER_REAL_MASTER)
#define FWD (CLUSTER_R4_OWNER_REAL_MASTER | CLUSTER_R4_OWNER_HOLDER_LMON)
#define LMS CLUSTER_R4_OWNER_HOLDER_LMS
#define UNDO (CLUSTER_R4_OWNER_HOLDER_LMON | CLUSTER_R4_OWNER_HOLDER_LMS | CLUSTER_R4_OWNER_ORIGIN)

#define DEFINE_CELL_TEST(test_name, state_value, event_value, next_value, alternate_value,         \
						 owner_value, action_value, text_value)                                    \
	UT_TEST(test_name)                                                                             \
	{                                                                                              \
		const ClusterR4TransitionCell *cell                                                        \
			= cluster_r4_transition_lookup((state_value), (event_value));                          \
		UT_ASSERT_NOT_NULL(cell);                                                                  \
		if (cell != NULL) {                                                                        \
			UT_ASSERT_EQ(cell->next_state, (next_value));                                          \
			UT_ASSERT_EQ(cell->alternate_state, (alternate_value));                                \
			UT_ASSERT_EQ(cell->owner_mask, (owner_value));                                         \
			UT_ASSERT_EQ(cell->action, (action_value));                                            \
			UT_ASSERT_STR_EQ(cell->spec_action, (text_value));                                     \
		}                                                                                          \
	}

/* E — EMPTY. */
DEFINE_CELL_TEST(test_01_e_valid, CLUSTER_R4_STATE_EMPTY, CLUSTER_R4_EVENT_VALID,
				 CLUSTER_R4_STATE_ROUTING, NONE, REQ, CLUSTER_R4_ACTION_ARM_BEFORE_SEND,
				 "R/arm-before-send")
DEFINE_CELL_TEST(test_02_e_duplicate, CLUSTER_R4_STATE_EMPTY, CLUSTER_R4_EVENT_DUPLICATE,
				 CLUSTER_R4_STATE_EMPTY, NONE, REQ, CLUSTER_R4_ACTION_DROP, "E/drop")
DEFINE_CELL_TEST(test_03_e_stale, CLUSTER_R4_STATE_EMPTY, CLUSTER_R4_EVENT_STALE,
				 CLUSTER_R4_STATE_EMPTY, NONE, REQ, CLUSTER_R4_ACTION_DROP, "E/drop")
DEFINE_CELL_TEST(test_04_e_timeout, CLUSTER_R4_STATE_EMPTY, CLUSTER_R4_EVENT_TIMEOUT,
				 CLUSTER_R4_STATE_EMPTY, NONE, REQ, CLUSTER_R4_ACTION_DROP, "E/drop")
DEFINE_CELL_TEST(test_05_e_cancel, CLUSTER_R4_STATE_EMPTY, CLUSTER_R4_EVENT_CANCEL,
				 CLUSTER_R4_STATE_CANCELLED, NONE, REQ, CLUSTER_R4_ACTION_NO_SEND, "K/no-send")
DEFINE_CELL_TEST(test_06_e_death, CLUSTER_R4_STATE_EMPTY, CLUSTER_R4_EVENT_DEATH,
				 CLUSTER_R4_STATE_EMPTY, NONE, REQ, CLUSTER_R4_ACTION_DROP, "E/drop")
DEFINE_CELL_TEST(test_07_e_reconfig, CLUSTER_R4_STATE_EMPTY, CLUSTER_R4_EVENT_RECONFIG,
				 CLUSTER_R4_STATE_EMPTY, NONE, REQ, CLUSTER_R4_ACTION_DROP, "E/drop")
DEFINE_CELL_TEST(test_08_e_capacity, CLUSTER_R4_STATE_EMPTY, CLUSTER_R4_EVENT_CAPACITY,
				 CLUSTER_R4_STATE_RETRYABLE, NONE, REQ, CLUSTER_R4_ACTION_RETRY, "T/retry")
DEFINE_CELL_TEST(test_09_e_malformed, CLUSTER_R4_STATE_EMPTY, CLUSTER_R4_EVENT_MALFORMED,
				 CLUSTER_R4_STATE_FAIL_CLOSED, NONE, REQ, CLUSTER_R4_ACTION_FAIL_PROTOCOL,
				 "X/FC(protocol)")

/* R — ROUTING. */
DEFINE_CELL_TEST(test_10_r_valid, CLUSTER_R4_STATE_ROUTING, CLUSTER_R4_EVENT_VALID,
				 CLUSTER_R4_STATE_FORWARDED, NONE, ROUTE, CLUSTER_R4_ACTION_MASTER_FORWARD,
				 "F/master selects+forwards")
DEFINE_CELL_TEST(test_11_r_duplicate, CLUSTER_R4_STATE_ROUTING, CLUSTER_R4_EVENT_DUPLICATE,
				 CLUSTER_R4_STATE_ROUTING, NONE, ROUTE, CLUSTER_R4_ACTION_REPLAY_ROUTE,
				 "R/replay same route")
DEFINE_CELL_TEST(test_12_r_stale, CLUSTER_R4_STATE_ROUTING, CLUSTER_R4_EVENT_STALE,
				 CLUSTER_R4_STATE_RETRYABLE, NONE, ROUTE, CLUSTER_R4_ACTION_RETRY, "T/retry")
DEFINE_CELL_TEST(test_13_r_timeout, CLUSTER_R4_STATE_ROUTING, CLUSTER_R4_EVENT_TIMEOUT,
				 CLUSTER_R4_STATE_RETRYABLE, NONE, ROUTE, CLUSTER_R4_ACTION_CLOSE_ATTEMPT,
				 "T/close attempt")
DEFINE_CELL_TEST(test_14_r_cancel, CLUSTER_R4_STATE_ROUTING, CLUSTER_R4_EVENT_CANCEL,
				 CLUSTER_R4_STATE_CANCELLED, NONE, ROUTE, CLUSTER_R4_ACTION_CANCEL_ROUTE,
				 "K/cancel route")
DEFINE_CELL_TEST(test_15_r_death, CLUSTER_R4_STATE_ROUTING, CLUSTER_R4_EVENT_DEATH,
				 CLUSTER_R4_STATE_RETRYABLE, NONE, ROUTE, CLUSTER_R4_ACTION_RETRY, "T/retry")
DEFINE_CELL_TEST(test_16_r_reconfig, CLUSTER_R4_STATE_ROUTING, CLUSTER_R4_EVENT_RECONFIG,
				 CLUSTER_R4_STATE_RETRYABLE, NONE, ROUTE, CLUSTER_R4_ACTION_STALE_ROUTE,
				 "T/stale route")
DEFINE_CELL_TEST(test_17_r_capacity, CLUSTER_R4_STATE_ROUTING, CLUSTER_R4_EVENT_CAPACITY,
				 CLUSTER_R4_STATE_RETRYABLE, NONE, ROUTE, CLUSTER_R4_ACTION_RETRY, "T/retry")
DEFINE_CELL_TEST(test_18_r_malformed, CLUSTER_R4_STATE_ROUTING, CLUSTER_R4_EVENT_MALFORMED,
				 CLUSTER_R4_STATE_FAIL_CLOSED, NONE, ROUTE, CLUSTER_R4_ACTION_FAIL_PROTOCOL,
				 "X/FC(protocol)")

/* F — FORWARDED. */
DEFINE_CELL_TEST(test_19_f_valid, CLUSTER_R4_STATE_FORWARDED, CLUSTER_R4_EVENT_VALID,
				 CLUSTER_R4_STATE_BUILDING, NONE, FWD, CLUSTER_R4_ACTION_HOLDER_STABLE_COPY,
				 "B/holder stable copy")
DEFINE_CELL_TEST(test_20_f_duplicate, CLUSTER_R4_STATE_FORWARDED, CLUSTER_R4_EVENT_DUPLICATE,
				 CLUSTER_R4_STATE_FORWARDED, NONE, FWD, CLUSTER_R4_ACTION_DROP_OR_REPLAY,
				 "F/drop or replay")
DEFINE_CELL_TEST(test_21_f_stale, CLUSTER_R4_STATE_FORWARDED, CLUSTER_R4_EVENT_STALE,
				 CLUSTER_R4_STATE_RETRYABLE, NONE, FWD, CLUSTER_R4_ACTION_RETRY, "T/retry")
DEFINE_CELL_TEST(test_22_f_timeout, CLUSTER_R4_STATE_FORWARDED, CLUSTER_R4_EVENT_TIMEOUT,
				 CLUSTER_R4_STATE_RETRYABLE, NONE, FWD, CLUSTER_R4_ACTION_CLOSE_ATTEMPT,
				 "T/close attempt")
DEFINE_CELL_TEST(test_23_f_cancel, CLUSTER_R4_STATE_FORWARDED, CLUSTER_R4_EVENT_CANCEL,
				 CLUSTER_R4_STATE_CANCELLED, NONE, FWD, CLUSTER_R4_ACTION_CANCEL_SLOT,
				 "K/cancel slot")
DEFINE_CELL_TEST(test_24_f_death, CLUSTER_R4_STATE_FORWARDED, CLUSTER_R4_EVENT_DEATH,
				 CLUSTER_R4_STATE_RETRYABLE, NONE, FWD, CLUSTER_R4_ACTION_RETRY, "T/retry")
DEFINE_CELL_TEST(test_25_f_reconfig, CLUSTER_R4_STATE_FORWARDED, CLUSTER_R4_EVENT_RECONFIG,
				 CLUSTER_R4_STATE_RETRYABLE, NONE, FWD, CLUSTER_R4_ACTION_STALE_SLOT,
				 "T/stale slot")
DEFINE_CELL_TEST(test_26_f_capacity, CLUSTER_R4_STATE_FORWARDED, CLUSTER_R4_EVENT_CAPACITY,
				 CLUSTER_R4_STATE_RETRYABLE, NONE, FWD, CLUSTER_R4_ACTION_RETRY, "T/retry")
DEFINE_CELL_TEST(test_27_f_malformed, CLUSTER_R4_STATE_FORWARDED, CLUSTER_R4_EVENT_MALFORMED,
				 CLUSTER_R4_STATE_FAIL_CLOSED, NONE, FWD, CLUSTER_R4_ACTION_FAIL_PROTOCOL,
				 "X/FC(protocol)")

/* B — BUILDING. */
DEFINE_CELL_TEST(test_28_b_valid, CLUSTER_R4_STATE_BUILDING, CLUSTER_R4_EVENT_VALID,
				 CLUSTER_R4_STATE_WAIT_UNDO, CLUSTER_R4_STATE_REPLIED, LMS,
				 CLUSTER_R4_ACTION_REQUEST_UNDO_OR_PUBLISH,
				 "U/request foreign undo or P/publish result")
DEFINE_CELL_TEST(test_29_b_duplicate, CLUSTER_R4_STATE_BUILDING, CLUSTER_R4_EVENT_DUPLICATE,
				 CLUSTER_R4_STATE_BUILDING, NONE, LMS, CLUSTER_R4_ACTION_DROP, "B/drop")
DEFINE_CELL_TEST(test_30_b_stale, CLUSTER_R4_STATE_BUILDING, CLUSTER_R4_EVENT_STALE,
				 CLUSTER_R4_STATE_RETRYABLE, NONE, LMS, CLUSTER_R4_ACTION_RETRY, "T/retry")
DEFINE_CELL_TEST(test_31_b_timeout, CLUSTER_R4_STATE_BUILDING, CLUSTER_R4_EVENT_TIMEOUT,
				 CLUSTER_R4_STATE_RETRYABLE, NONE, LMS, CLUSTER_R4_ACTION_ABORT_SCRATCH,
				 "T/abort scratch")
DEFINE_CELL_TEST(test_32_b_cancel, CLUSTER_R4_STATE_BUILDING, CLUSTER_R4_EVENT_CANCEL,
				 CLUSTER_R4_STATE_CANCELLED, NONE, LMS, CLUSTER_R4_ACTION_ABORT_SCRATCH,
				 "K/abort scratch")
DEFINE_CELL_TEST(test_33_b_death, CLUSTER_R4_STATE_BUILDING, CLUSTER_R4_EVENT_DEATH,
				 CLUSTER_R4_STATE_RETRYABLE, NONE, LMS, CLUSTER_R4_ACTION_RETRY, "T/retry")
DEFINE_CELL_TEST(test_34_b_reconfig, CLUSTER_R4_STATE_BUILDING, CLUSTER_R4_EVENT_RECONFIG,
				 CLUSTER_R4_STATE_RETRYABLE, NONE, LMS, CLUSTER_R4_ACTION_ABORT_SCRATCH,
				 "T/abort scratch")
DEFINE_CELL_TEST(test_35_b_capacity, CLUSTER_R4_STATE_BUILDING, CLUSTER_R4_EVENT_CAPACITY,
				 CLUSTER_R4_STATE_RETRYABLE, NONE, LMS, CLUSTER_R4_ACTION_RETRY, "T/retry")
DEFINE_CELL_TEST(test_36_b_malformed, CLUSTER_R4_STATE_BUILDING, CLUSTER_R4_EVENT_MALFORMED,
				 CLUSTER_R4_STATE_FAIL_CLOSED, NONE, LMS, CLUSTER_R4_ACTION_FAIL_DATA_PROTOCOL,
				 "X/FC(data/protocol)")

/* U — WAIT_UNDO. */
DEFINE_CELL_TEST(test_37_u_valid, CLUSTER_R4_STATE_WAIT_UNDO, CLUSTER_R4_EVENT_VALID,
				 CLUSTER_R4_STATE_BUILDING, NONE, UNDO, CLUSTER_R4_ACTION_EXACT_UNDO_REPLY,
				 "B/exact undo reply")
DEFINE_CELL_TEST(test_38_u_duplicate, CLUSTER_R4_STATE_WAIT_UNDO, CLUSTER_R4_EVENT_DUPLICATE,
				 CLUSTER_R4_STATE_WAIT_UNDO, NONE, UNDO, CLUSTER_R4_ACTION_DROP, "U/drop")
DEFINE_CELL_TEST(test_39_u_stale, CLUSTER_R4_STATE_WAIT_UNDO, CLUSTER_R4_EVENT_STALE,
				 CLUSTER_R4_STATE_RETRYABLE, NONE, UNDO, CLUSTER_R4_ACTION_RETRY, "T/retry")
DEFINE_CELL_TEST(test_40_u_timeout, CLUSTER_R4_STATE_WAIT_UNDO, CLUSTER_R4_EVENT_TIMEOUT,
				 CLUSTER_R4_STATE_RETRYABLE, NONE, UNDO, CLUSTER_R4_ACTION_ABORT_SCRATCH,
				 "T/abort scratch")
DEFINE_CELL_TEST(test_41_u_cancel, CLUSTER_R4_STATE_WAIT_UNDO, CLUSTER_R4_EVENT_CANCEL,
				 CLUSTER_R4_STATE_CANCELLED, NONE, UNDO, CLUSTER_R4_ACTION_ABORT_SCRATCH,
				 "K/abort scratch")
DEFINE_CELL_TEST(test_42_u_death, CLUSTER_R4_STATE_WAIT_UNDO, CLUSTER_R4_EVENT_DEATH,
				 CLUSTER_R4_STATE_RETRYABLE, NONE, UNDO, CLUSTER_R4_ACTION_RETRY, "T/retry")
DEFINE_CELL_TEST(test_43_u_reconfig, CLUSTER_R4_STATE_WAIT_UNDO, CLUSTER_R4_EVENT_RECONFIG,
				 CLUSTER_R4_STATE_RETRYABLE, NONE, UNDO, CLUSTER_R4_ACTION_ABORT_SCRATCH,
				 "T/abort scratch")
DEFINE_CELL_TEST(test_44_u_capacity, CLUSTER_R4_STATE_WAIT_UNDO, CLUSTER_R4_EVENT_CAPACITY,
				 CLUSTER_R4_STATE_RETRYABLE, NONE, UNDO, CLUSTER_R4_ACTION_RETRY, "T/retry")
DEFINE_CELL_TEST(test_45_u_malformed, CLUSTER_R4_STATE_WAIT_UNDO, CLUSTER_R4_EVENT_MALFORMED,
				 CLUSTER_R4_STATE_FAIL_CLOSED, NONE, UNDO, CLUSTER_R4_ACTION_FAIL_DATA_PROTOCOL,
				 "X/FC(data/protocol)")

/* P — REPLIED. */
DEFINE_CELL_TEST(test_46_p_valid, CLUSTER_R4_STATE_REPLIED, CLUSTER_R4_EVENT_VALID,
				 CLUSTER_R4_STATE_CONSUMED, NONE, REQ, CLUSTER_R4_ACTION_CONSUMER_CAS,
				 "C/exact consumer CAS")
DEFINE_CELL_TEST(test_47_p_duplicate, CLUSTER_R4_STATE_REPLIED, CLUSTER_R4_EVENT_DUPLICATE,
				 CLUSTER_R4_STATE_REPLIED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "P/drop")
DEFINE_CELL_TEST(test_48_p_stale, CLUSTER_R4_STATE_REPLIED, CLUSTER_R4_EVENT_STALE,
				 CLUSTER_R4_STATE_REPLIED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "P/drop")
DEFINE_CELL_TEST(test_49_p_timeout, CLUSTER_R4_STATE_REPLIED, CLUSTER_R4_EVENT_TIMEOUT,
				 CLUSTER_R4_STATE_REPLIED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "P/drop")
DEFINE_CELL_TEST(test_50_p_cancel, CLUSTER_R4_STATE_REPLIED, CLUSTER_R4_EVENT_CANCEL,
				 CLUSTER_R4_STATE_CANCELLED, NONE, REQ, CLUSTER_R4_ACTION_DROP_RESULT,
				 "K/drop result")
DEFINE_CELL_TEST(test_51_p_death, CLUSTER_R4_STATE_REPLIED, CLUSTER_R4_EVENT_DEATH,
				 CLUSTER_R4_STATE_REPLIED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "P/drop")
DEFINE_CELL_TEST(test_52_p_reconfig, CLUSTER_R4_STATE_REPLIED, CLUSTER_R4_EVENT_RECONFIG,
				 CLUSTER_R4_STATE_REPLIED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "P/drop")
DEFINE_CELL_TEST(test_53_p_capacity, CLUSTER_R4_STATE_REPLIED, CLUSTER_R4_EVENT_CAPACITY,
				 CLUSTER_R4_STATE_REPLIED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "P/drop")
DEFINE_CELL_TEST(test_54_p_malformed, CLUSTER_R4_STATE_REPLIED, CLUSTER_R4_EVENT_MALFORMED,
				 CLUSTER_R4_STATE_REPLIED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "P/drop")

/* C — CONSUMED, absorbing. */
DEFINE_CELL_TEST(test_55_c_valid, CLUSTER_R4_STATE_CONSUMED, CLUSTER_R4_EVENT_VALID,
				 CLUSTER_R4_STATE_CONSUMED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "C/drop")
DEFINE_CELL_TEST(test_56_c_duplicate, CLUSTER_R4_STATE_CONSUMED, CLUSTER_R4_EVENT_DUPLICATE,
				 CLUSTER_R4_STATE_CONSUMED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "C/drop")
DEFINE_CELL_TEST(test_57_c_stale, CLUSTER_R4_STATE_CONSUMED, CLUSTER_R4_EVENT_STALE,
				 CLUSTER_R4_STATE_CONSUMED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "C/drop")
DEFINE_CELL_TEST(test_58_c_timeout, CLUSTER_R4_STATE_CONSUMED, CLUSTER_R4_EVENT_TIMEOUT,
				 CLUSTER_R4_STATE_CONSUMED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "C/drop")
DEFINE_CELL_TEST(test_59_c_cancel, CLUSTER_R4_STATE_CONSUMED, CLUSTER_R4_EVENT_CANCEL,
				 CLUSTER_R4_STATE_CONSUMED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "C/drop")
DEFINE_CELL_TEST(test_60_c_death, CLUSTER_R4_STATE_CONSUMED, CLUSTER_R4_EVENT_DEATH,
				 CLUSTER_R4_STATE_CONSUMED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "C/drop")
DEFINE_CELL_TEST(test_61_c_reconfig, CLUSTER_R4_STATE_CONSUMED, CLUSTER_R4_EVENT_RECONFIG,
				 CLUSTER_R4_STATE_CONSUMED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "C/drop")
DEFINE_CELL_TEST(test_62_c_capacity, CLUSTER_R4_STATE_CONSUMED, CLUSTER_R4_EVENT_CAPACITY,
				 CLUSTER_R4_STATE_CONSUMED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "C/drop")
DEFINE_CELL_TEST(test_63_c_malformed, CLUSTER_R4_STATE_CONSUMED, CLUSTER_R4_EVENT_MALFORMED,
				 CLUSTER_R4_STATE_CONSUMED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "C/drop")

/* T — RETRYABLE. */
DEFINE_CELL_TEST(test_64_t_valid, CLUSTER_R4_STATE_RETRYABLE, CLUSTER_R4_EVENT_VALID,
				 CLUSTER_R4_STATE_ROUTING, NONE, REQ, CLUSTER_R4_ACTION_NEW_REQUEST,
				 "R/new request id after typed close")
DEFINE_CELL_TEST(test_65_t_duplicate, CLUSTER_R4_STATE_RETRYABLE, CLUSTER_R4_EVENT_DUPLICATE,
				 CLUSTER_R4_STATE_RETRYABLE, NONE, REQ, CLUSTER_R4_ACTION_DROP, "T/drop")
DEFINE_CELL_TEST(test_66_t_stale, CLUSTER_R4_STATE_RETRYABLE, CLUSTER_R4_EVENT_STALE,
				 CLUSTER_R4_STATE_RETRYABLE, NONE, REQ, CLUSTER_R4_ACTION_DROP, "T/drop")
DEFINE_CELL_TEST(test_67_t_timeout, CLUSTER_R4_STATE_RETRYABLE, CLUSTER_R4_EVENT_TIMEOUT,
				 CLUSTER_R4_STATE_FAIL_CLOSED, NONE, REQ, CLUSTER_R4_ACTION_OVERALL_DEADLINE,
				 "X/overall deadline")
DEFINE_CELL_TEST(test_68_t_cancel, CLUSTER_R4_STATE_RETRYABLE, CLUSTER_R4_EVENT_CANCEL,
				 CLUSTER_R4_STATE_CANCELLED, NONE, REQ, CLUSTER_R4_ACTION_CLEANUP, "K/cleanup")
DEFINE_CELL_TEST(test_69_t_death, CLUSTER_R4_STATE_RETRYABLE, CLUSTER_R4_EVENT_DEATH,
				 CLUSTER_R4_STATE_RETRYABLE, NONE, REQ, CLUSTER_R4_ACTION_WAIT_TOPOLOGY,
				 "T/wait topology")
DEFINE_CELL_TEST(test_70_t_reconfig, CLUSTER_R4_STATE_RETRYABLE, CLUSTER_R4_EVENT_RECONFIG,
				 CLUSTER_R4_STATE_RETRYABLE, NONE, REQ, CLUSTER_R4_ACTION_WAIT_ADMISSION,
				 "T/wait admission")
DEFINE_CELL_TEST(test_71_t_capacity, CLUSTER_R4_STATE_RETRYABLE, CLUSTER_R4_EVENT_CAPACITY,
				 CLUSTER_R4_STATE_RETRYABLE, NONE, REQ, CLUSTER_R4_ACTION_BACKOFF, "T/backoff")
DEFINE_CELL_TEST(test_72_t_malformed, CLUSTER_R4_STATE_RETRYABLE, CLUSTER_R4_EVENT_MALFORMED,
				 CLUSTER_R4_STATE_FAIL_CLOSED, NONE, REQ, CLUSTER_R4_ACTION_FAIL_PROTOCOL,
				 "X/FC(protocol)")

/* X — FAIL_CLOSED, absorbing. */
DEFINE_CELL_TEST(test_73_x_valid, CLUSTER_R4_STATE_FAIL_CLOSED, CLUSTER_R4_EVENT_VALID,
				 CLUSTER_R4_STATE_FAIL_CLOSED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "X/drop")
DEFINE_CELL_TEST(test_74_x_duplicate, CLUSTER_R4_STATE_FAIL_CLOSED, CLUSTER_R4_EVENT_DUPLICATE,
				 CLUSTER_R4_STATE_FAIL_CLOSED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "X/drop")
DEFINE_CELL_TEST(test_75_x_stale, CLUSTER_R4_STATE_FAIL_CLOSED, CLUSTER_R4_EVENT_STALE,
				 CLUSTER_R4_STATE_FAIL_CLOSED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "X/drop")
DEFINE_CELL_TEST(test_76_x_timeout, CLUSTER_R4_STATE_FAIL_CLOSED, CLUSTER_R4_EVENT_TIMEOUT,
				 CLUSTER_R4_STATE_FAIL_CLOSED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "X/drop")
DEFINE_CELL_TEST(test_77_x_cancel, CLUSTER_R4_STATE_FAIL_CLOSED, CLUSTER_R4_EVENT_CANCEL,
				 CLUSTER_R4_STATE_FAIL_CLOSED, NONE, REQ, CLUSTER_R4_ACTION_CLEANUP, "X/cleanup")
DEFINE_CELL_TEST(test_78_x_death, CLUSTER_R4_STATE_FAIL_CLOSED, CLUSTER_R4_EVENT_DEATH,
				 CLUSTER_R4_STATE_FAIL_CLOSED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "X/drop")
DEFINE_CELL_TEST(test_79_x_reconfig, CLUSTER_R4_STATE_FAIL_CLOSED, CLUSTER_R4_EVENT_RECONFIG,
				 CLUSTER_R4_STATE_FAIL_CLOSED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "X/drop")
DEFINE_CELL_TEST(test_80_x_capacity, CLUSTER_R4_STATE_FAIL_CLOSED, CLUSTER_R4_EVENT_CAPACITY,
				 CLUSTER_R4_STATE_FAIL_CLOSED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "X/drop")
DEFINE_CELL_TEST(test_81_x_malformed, CLUSTER_R4_STATE_FAIL_CLOSED, CLUSTER_R4_EVENT_MALFORMED,
				 CLUSTER_R4_STATE_FAIL_CLOSED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "X/drop")

/* K — CANCELLED, absorbing. */
DEFINE_CELL_TEST(test_82_k_valid, CLUSTER_R4_STATE_CANCELLED, CLUSTER_R4_EVENT_VALID,
				 CLUSTER_R4_STATE_CANCELLED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "K/drop")
DEFINE_CELL_TEST(test_83_k_duplicate, CLUSTER_R4_STATE_CANCELLED, CLUSTER_R4_EVENT_DUPLICATE,
				 CLUSTER_R4_STATE_CANCELLED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "K/drop")
DEFINE_CELL_TEST(test_84_k_stale, CLUSTER_R4_STATE_CANCELLED, CLUSTER_R4_EVENT_STALE,
				 CLUSTER_R4_STATE_CANCELLED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "K/drop")
DEFINE_CELL_TEST(test_85_k_timeout, CLUSTER_R4_STATE_CANCELLED, CLUSTER_R4_EVENT_TIMEOUT,
				 CLUSTER_R4_STATE_CANCELLED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "K/drop")
DEFINE_CELL_TEST(test_86_k_cancel, CLUSTER_R4_STATE_CANCELLED, CLUSTER_R4_EVENT_CANCEL,
				 CLUSTER_R4_STATE_CANCELLED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "K/drop")
DEFINE_CELL_TEST(test_87_k_death, CLUSTER_R4_STATE_CANCELLED, CLUSTER_R4_EVENT_DEATH,
				 CLUSTER_R4_STATE_CANCELLED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "K/drop")
DEFINE_CELL_TEST(test_88_k_reconfig, CLUSTER_R4_STATE_CANCELLED, CLUSTER_R4_EVENT_RECONFIG,
				 CLUSTER_R4_STATE_CANCELLED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "K/drop")
DEFINE_CELL_TEST(test_89_k_capacity, CLUSTER_R4_STATE_CANCELLED, CLUSTER_R4_EVENT_CAPACITY,
				 CLUSTER_R4_STATE_CANCELLED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "K/drop")
DEFINE_CELL_TEST(test_90_k_malformed, CLUSTER_R4_STATE_CANCELLED, CLUSTER_R4_EVENT_MALFORMED,
				 CLUSTER_R4_STATE_CANCELLED, NONE, REQ, CLUSTER_R4_ACTION_DROP, "K/drop")

/* Physical LMS slot ABI: legacy ordinals stay fixed; R4 is append-only. */
UT_TEST(test_91_physical_lms_slot_abi)
{
	UT_ASSERT_EQ(CLUSTER_LMS_CR_FREE, 0);
	UT_ASSERT_EQ(CLUSTER_LMS_CR_PENDING, 1);
	UT_ASSERT_EQ(CLUSTER_LMS_CR_BUSY, 2);
	UT_ASSERT_EQ(CLUSTER_LMS_CR_READY, 3);
	UT_ASSERT_EQ(CLUSTER_LMS_CR_FILLING, 4);
	UT_ASSERT_EQ(CLUSTER_LMS_SLOT_KIND_CR, 0);
	UT_ASSERT_EQ(CLUSTER_LMS_SLOT_KIND_UNDO_FETCH, 1);
	UT_ASSERT_EQ(CLUSTER_LMS_SLOT_KIND_UNDO_VERDICT, 2);
	UT_ASSERT_EQ(CLUSTER_LMS_SLOT_KIND_UNDO_MULTI_VERDICT, 3);

	UT_ASSERT_EQ(CLUSTER_LMS_SLOT_KIND_R4_CR_BUILD, 4);
	UT_ASSERT_EQ(CLUSTER_LMS_CR_R4_QUEUED, 5);
	UT_ASSERT_EQ(CLUSTER_LMS_CR_R4_BUILDING, 6);
	UT_ASSERT_EQ(CLUSTER_LMS_CR_R4_NEED_UNDO, 7);
	UT_ASSERT_EQ(CLUSTER_LMS_CR_R4_UNDO_INFLIGHT, 8);
	UT_ASSERT_EQ(CLUSTER_LMS_CR_R4_UNDO_READY, 9);
	UT_ASSERT_EQ(CLUSTER_LMS_CR_R4_READY_FULL, 10);
	UT_ASSERT_EQ(CLUSTER_LMS_CR_R4_READY_RETRY, 11);
	UT_ASSERT_EQ(CLUSTER_LMS_CR_R4_READY_FAIL, 12);
	UT_ASSERT_EQ(CLUSTER_LMS_CR_R4_CANCELLED, 13);
	UT_ASSERT_EQ(CLUSTER_LMS_CR_R4_SHIPPING, 14);
	UT_ASSERT_EQ(CLUSTER_LMS_CR_R4_RECLAIMING, 15);

	UT_ASSERT_EQ((int)sizeof(ClusterR4CrOwnerStamp), 32);
	UT_ASSERT_EQ((int)offsetof(ClusterR4CrSlotExtension, owner), 80);
	UT_ASSERT_EQ((int)offsetof(ClusterR4CrSlotExtension, slot_generation), 112);
	UT_ASSERT_EQ((int)sizeof(ClusterR4CrSlotExtension), 256);

	UT_ASSERT_EQ((int)sizeof(((ClusterLmsCrSlot *)0)->result_page), BLCKSZ);
	UT_ASSERT_EQ((int)offsetof(ClusterLmsCrSlot, r4),
				 (int)offsetof(ClusterLmsCrSlot, result_page) + BLCKSZ);
	UT_ASSERT_EQ((int)offsetof(ClusterLmsCrSlot, foreign_undo_page),
				 (int)offsetof(ClusterLmsCrSlot, r4) + 256);
	UT_ASSERT_EQ((int)sizeof(((ClusterLmsCrSlot *)0)->foreign_undo_page), BLCKSZ);
	UT_ASSERT_EQ((int)sizeof(ClusterLmsCrSlot), (int)offsetof(ClusterLmsCrSlot, r4) + 256 + BLCKSZ);
	UT_ASSERT_EQ((int)(sizeof(ClusterR4CrSlotExtension) + BLCKSZ), 8448);
	UT_ASSERT_EQ((int)(CLUSTER_LMS_CR_SLOTS * (sizeof(ClusterR4CrSlotExtension) + BLCKSZ)), 33792);
}

/* D4-B exact append-only LMS incarnation/drain control ABI. */
UT_TEST(test_92_physical_lms_r4_control_abi)
{
	UT_ASSERT_EQ((int)offsetof(ClusterLmsR4Controls, data_worker_incarnation), 0);
	UT_ASSERT_EQ((int)sizeof(((ClusterLmsR4Controls *)0)->data_worker_incarnation), 64);
	UT_ASSERT_EQ((int)offsetof(ClusterLmsR4Controls, drain_request_generation), 64);
	UT_ASSERT_EQ((int)offsetof(ClusterLmsR4Controls, drain_ack_generation), 72);
	UT_ASSERT_EQ((int)sizeof(ClusterLmsR4Controls), 80);

	UT_ASSERT_EQ((int)offsetof(ClusterLmsSharedState, r4_controls),
				 (int)sizeof(ClusterLmsSharedState) - 80);
	UT_ASSERT_EQ((int)(CLUSTER_LMS_CR_SLOTS * (sizeof(ClusterR4CrSlotExtension) + BLCKSZ)
					   + sizeof(ClusterLmsR4Controls)),
				 33872);
}

int
main(void)
{
	UT_PLAN(92);
	UT_RUN(test_01_e_valid);
	UT_RUN(test_02_e_duplicate);
	UT_RUN(test_03_e_stale);
	UT_RUN(test_04_e_timeout);
	UT_RUN(test_05_e_cancel);
	UT_RUN(test_06_e_death);
	UT_RUN(test_07_e_reconfig);
	UT_RUN(test_08_e_capacity);
	UT_RUN(test_09_e_malformed);
	UT_RUN(test_10_r_valid);
	UT_RUN(test_11_r_duplicate);
	UT_RUN(test_12_r_stale);
	UT_RUN(test_13_r_timeout);
	UT_RUN(test_14_r_cancel);
	UT_RUN(test_15_r_death);
	UT_RUN(test_16_r_reconfig);
	UT_RUN(test_17_r_capacity);
	UT_RUN(test_18_r_malformed);
	UT_RUN(test_19_f_valid);
	UT_RUN(test_20_f_duplicate);
	UT_RUN(test_21_f_stale);
	UT_RUN(test_22_f_timeout);
	UT_RUN(test_23_f_cancel);
	UT_RUN(test_24_f_death);
	UT_RUN(test_25_f_reconfig);
	UT_RUN(test_26_f_capacity);
	UT_RUN(test_27_f_malformed);
	UT_RUN(test_28_b_valid);
	UT_RUN(test_29_b_duplicate);
	UT_RUN(test_30_b_stale);
	UT_RUN(test_31_b_timeout);
	UT_RUN(test_32_b_cancel);
	UT_RUN(test_33_b_death);
	UT_RUN(test_34_b_reconfig);
	UT_RUN(test_35_b_capacity);
	UT_RUN(test_36_b_malformed);
	UT_RUN(test_37_u_valid);
	UT_RUN(test_38_u_duplicate);
	UT_RUN(test_39_u_stale);
	UT_RUN(test_40_u_timeout);
	UT_RUN(test_41_u_cancel);
	UT_RUN(test_42_u_death);
	UT_RUN(test_43_u_reconfig);
	UT_RUN(test_44_u_capacity);
	UT_RUN(test_45_u_malformed);
	UT_RUN(test_46_p_valid);
	UT_RUN(test_47_p_duplicate);
	UT_RUN(test_48_p_stale);
	UT_RUN(test_49_p_timeout);
	UT_RUN(test_50_p_cancel);
	UT_RUN(test_51_p_death);
	UT_RUN(test_52_p_reconfig);
	UT_RUN(test_53_p_capacity);
	UT_RUN(test_54_p_malformed);
	UT_RUN(test_55_c_valid);
	UT_RUN(test_56_c_duplicate);
	UT_RUN(test_57_c_stale);
	UT_RUN(test_58_c_timeout);
	UT_RUN(test_59_c_cancel);
	UT_RUN(test_60_c_death);
	UT_RUN(test_61_c_reconfig);
	UT_RUN(test_62_c_capacity);
	UT_RUN(test_63_c_malformed);
	UT_RUN(test_64_t_valid);
	UT_RUN(test_65_t_duplicate);
	UT_RUN(test_66_t_stale);
	UT_RUN(test_67_t_timeout);
	UT_RUN(test_68_t_cancel);
	UT_RUN(test_69_t_death);
	UT_RUN(test_70_t_reconfig);
	UT_RUN(test_71_t_capacity);
	UT_RUN(test_72_t_malformed);
	UT_RUN(test_73_x_valid);
	UT_RUN(test_74_x_duplicate);
	UT_RUN(test_75_x_stale);
	UT_RUN(test_76_x_timeout);
	UT_RUN(test_77_x_cancel);
	UT_RUN(test_78_x_death);
	UT_RUN(test_79_x_reconfig);
	UT_RUN(test_80_x_capacity);
	UT_RUN(test_81_x_malformed);
	UT_RUN(test_82_k_valid);
	UT_RUN(test_83_k_duplicate);
	UT_RUN(test_84_k_stale);
	UT_RUN(test_85_k_timeout);
	UT_RUN(test_86_k_cancel);
	UT_RUN(test_87_k_death);
	UT_RUN(test_88_k_reconfig);
	UT_RUN(test_89_k_capacity);
	UT_RUN(test_90_k_malformed);
	UT_RUN(test_91_physical_lms_slot_abi);
	UT_RUN(test_92_physical_lms_r4_control_abi);
	UT_DONE();
	return ut_failed_count == 0 ? 0 : 1;
}
