#-------------------------------------------------------------------------
#
# 337_spec327_d3c_undo_wal_bytes_ab.pl
#	  spec-3.27 D3c — undo WAL-bytes A/B: bufmgr must not amplify vs legacy.
#
#	  D3b's first-cut bufmgr write path emitted an always-FPI (full 8KB page)
#	  RM_CLUSTER_UNDO record PER undo record, which measured ~15x the WAL of the
#	  legacy_pool path (deferred-merge + FPI-on-first-touch delta).  That WAL
#	  amplification -- not the buffer machinery -- was the dominant cause of the
#	  A+B+C write-tax regression (t/336).  D3c makes the bufmgr path use the SAME
#	  FPI-on-first-touch-since-checkpoint + 3-range delta representation as legacy
#	  (Q5-C keeps recovery path-based).
#
#	  This test runs an IDENTICAL fixed workload against a legacy_pool and a
#	  bufmgr instance and compares the WAL bytes each generates.  It isolates the
#	  undo WAL representation from the noisy TPS.  Gate: bufmgr WAL must be within
#	  a small multiple of legacy WAL (<= 3x) -- i.e. no gross per-record FPI
#	  amplification.  (Exact parity is a deferred-merge follow-up; this gate only
#	  proves the 15x defect is gone.)
#
# Copyright (c) 1996-2024, PostgreSQL Global Development Group
# Portions Copyright (c) 2026, pgrac contributors
#
# Author: SqlRush <sqlrush@gmail.com>
#
# IDENTIFICATION
#	  src/test/cluster_tap/t/337_spec327_d3c_undo_wal_bytes_ab.pl
#
# Spec: spec-3.27-undo-buffer-backed-model.md (D3c undo WAL representation)
#
#-------------------------------------------------------------------------

use strict;
use warnings;

use PostgreSQL::Test::Cluster;
use PostgreSQL::Test::Utils;
use Test::More;

my $UPDATES = $ENV{PGRAC_WAL_UPDATES} // 5000;
my $ROWS    = 1000;
my $RATIO_MAX = 3.0;    # bufmgr WAL must be <= 3x legacy (defect was ~15x)

# fsync off: we measure WAL *bytes* generated, not disk latency.  A high
# checkpoint budget keeps the first-touch FPI from re-arming mid-workload so the
# delta path dominates for both arms (matching a steady-state comparison).
my @perf_conf = (
	"autovacuum = off\n",
	"fsync = off\n",
	"shared_buffers = 128MB\n",
	"max_wal_size = 8GB\n",
	"checkpoint_timeout = 1h\n",
);

sub make_node
{
	my ($name, $backend) = @_;
	my $ic_port = PostgreSQL::Test::Cluster::get_free_port();
	my $node    = PostgreSQL::Test::Cluster->new($name);
	$node->init;
	$node->append_conf('postgresql.conf', "cluster.enabled = on\n");
	$node->append_conf('postgresql.conf', "cluster.node_id = 0\n");
	$node->append_conf('postgresql.conf', "cluster.allow_single_node = on\n");
	$node->append_conf('postgresql.conf', "cluster.undo_buffer_backend = $backend\n");
	$node->append_conf('postgresql.conf', $_) for @perf_conf;
	PostgreSQL::Test::Utils::append_to_file(
		$node->data_dir . '/pgrac.conf',
		"[cluster]\nname = $name\n\n[node.0]\ninterconnect_addr = 127.0.0.1:$ic_port\n\n");
	$node->start;
	return $node;
}

# WAL bytes generated by $UPDATES single-row UPDATEs (each its own xact) after a
# CHECKPOINT baseline.  Returns the byte count.
sub wal_for_workload
{
	my ($node) = @_;
	$node->safe_psql('postgres', 'DROP TABLE IF EXISTS w');
	$node->safe_psql('postgres', 'CREATE TABLE w(id int primary key, v text)');
	$node->safe_psql('postgres',
		"INSERT INTO w SELECT g, repeat('x',50) FROM generate_series(1,$ROWS) g");
	$node->safe_psql('postgres', 'CHECKPOINT');
	my $start = $node->safe_psql('postgres', 'SELECT pg_current_wal_lsn()');
	$node->safe_psql('postgres', qq{
		DO \$\$ BEGIN
			FOR i IN 1..$UPDATES LOOP
				UPDATE w SET v = v || 'y' WHERE id = (i % $ROWS) + 1;
			END LOOP;
		END \$\$;
	});
	my $bytes = $node->safe_psql('postgres',
		"SELECT pg_wal_lsn_diff(pg_current_wal_lsn(), '$start')::bigint");
	return defined $bytes ? $bytes + 0 : undef;
}

my $legacy = make_node('wal_legacy', 'legacy_pool');
my $bufmgr = make_node('wal_bufmgr', 'bufmgr');

is($bufmgr->safe_psql('postgres', 'SHOW cluster.undo_buffer_backend'),
	'bufmgr', 'bufmgr instance running undo_buffer_backend = bufmgr');

my $wl = wal_for_workload($legacy);
my $wb = wal_for_workload($bufmgr);

$legacy->stop;
$bufmgr->stop;

ok(defined $wl && $wl > 0, "legacy_pool produced WAL for the workload ($wl bytes)");
ok(defined $wb && $wb > 0, "bufmgr produced WAL for the workload ($wb bytes)");

SKIP:
{
	skip "WAL measurement failed", 1 unless defined $wl && $wl > 0 && defined $wb && $wb > 0;

	my $ratio = $wb / $wl;
	diag(sprintf("=== spec-3.27 D3c undo WAL A/B (%d updates over %d rows) ===",
		$UPDATES, $ROWS));
	diag(sprintf("  legacy_pool WAL = %d bytes  (%.1f B/update)", $wl, $wl / $UPDATES));
	diag(sprintf("  bufmgr      WAL = %d bytes  (%.1f B/update)", $wb, $wb / $UPDATES));
	diag(sprintf("  bufmgr / legacy ratio = %.2fx   (gate: <= %.1fx)", $ratio, $RATIO_MAX));

	ok($ratio <= $RATIO_MAX,
		sprintf("bufmgr undo WAL within %.1fx of legacy (got %.2fx) -- no per-record FPI amplification",
			$RATIO_MAX, $ratio));
}

done_testing();
